CREATE TABLE IF NOT EXISTS TODOS (
	ID INTEGER NOT NULL PRIMARY KEY,
    USERID INTEGER NOT NULL,
	TITLE VARCHAR(60) NOT NULL,
	COMPLETED VARCHAR(60) NOT NULL
);

INSERT INTO TODOS (ID, USERID, TITLE, COMPLETED) VALUES (1, 1, 'TITLE1','C1');
INSERT INTO TODOS (ID, USERID, TITLE, COMPLETED) VALUES (2, 2, 'TITLE2','C2');
INSERT INTO TODOS (ID, USERID, TITLE, COMPLETED) VALUES (3, 3, 'TITLE3','C3');